server:
  port: 8022

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.220.141:8848
        namespace: 832fb525-e351-485e-b984-78033ae04fda
    gateway:
      discovery:
        locator:
          enabled: true #开启gateway从nacos获取服务信息

      #路由数组
      routes: #路由数组 [路由：当请求满足某个条件的时候转发到指定的微服务上]
        #基于时间
        - id: dateTime_route
          uri: lb://consumer-demo
          order: 1
          predicates:
            - After=2019-12-31T23:59:59.789+08:00[Asia/Shanghai]
            - Before=2019-12-31T23:59:59.789+08:00[Asia/Shanghai]
            - Between=2019-12-31T23:59:59.789+08:00[Asia/Shanghai],2020-12-31T23:59:59.789+08:00[Asia/Shanghai]
        #基于cookies
        - id: cookie_route
          uri: lb://consumer-demo
          order: 1
          predicates:
            - Cookie=chocolate,value
      #基于请求头
        - id: header_route
          uri: lb://consumer-demo
          order: 1
          predicates:
            - Header=X-Request-Id, \d+
      #基于参数路由
        - id: param_route
          uri: lb://consumer-demo
          order: 1
          predicates:
            - Query=name,chenwei
      #基于path路由
        - id: consumer-demo  #当前路由标志，唯一,默认是uuid
          uri: lb://consumer-demo #请求最终要被转发的地址,lb代表的是负载均衡，后面跟的是微服务在nacos的标志
          order: 1 #路由优先级，数字越小代表路由的优先级越高
          predicates:  #断言(条件判断 ，返回值是boolean，转发请求要满足的条件)
            - Path=/consumerdemo/**  #当请求路径满足Path指定的规则时，此路由信息才会正常转发
            - After=2019-12-31T23:59:59.789+08:00[Asia/Shanghai]
          filters: #过滤器 （在请求传递过程中对其做一些处理）
            - StripPrefix=1 #在请求转发之前去掉一层路径
        #自定义路由
        - id: route_demo
          uri: http://www.baidu.com
          order: 1
          predicates:
            - Age=12,20

        - id: route_demo2
          uri: http://www.baidu.com
          order: 1
          predicates:
            - Token=123
          filters:
            - Log=true,false