server:
  port: 8020

spring:
  application:
    name: consumer-demo
  zipkin:
    base-url: http://192.168.37.130:9411 #zipkin server 的地址
    discovery-client-enabled: false #让nacos 把它当做一个url，而不是一个服务名
  sleuth:
    sampler:
      probability: 1.0 #采样百分比  0.0-1.0
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.220.141:8848
        namespace: 832fb525-e351-485e-b984-78033ae04fda
    sentinel:
      transport:
        #sentinel \u670D\u52A1\u5730\u5740
        dashboard: 127.0.0.1:8080
        #\u4EA4\u4E92\u7AEF\u53E3
        port: 8888
        #\u5173\u95ED\u52A0\u8F7D\u5EF6\u8FDF
      eager: true
#\u5F00\u542Fsentinel\u7194\u65AD\u5668
feign:
  sentinel:
    enabled: true

# \u7AEF\u70B9\u68C0\u67E5
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info