server:
  port: 8012
spring:
  application:
    name: provider-demo
    # nacos \u670D\u52A1\u5730\u5740
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.220.141:8848
        namespace: 832fb525-e351-485e-b984-78033ae04fda

# \u7AEF\u70B9\u68C0\u67E5
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: debug