server:
  port: 8012
spring:
  application:
    name: provider-demo
    # nacos \u670D\u52A1\u5730\u5740
  zipkin:
    base-url: http://127.0.0.1:9411 #zipkin server 的地址
    discovery-client-enabled: false #让nacos 把它当做一个url，而不是一个服务名
  sleuth:
    sampler:
      probability: 1.0 #采样百分比  0.0-1.0
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.220.141:8848
        namespace: 832fb525-e351-485e-b984-78033ae04fda

# \u7AEF\u70B9\u68C0\u67E5
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info